[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "BenchmarkDPFair"
version = "0.2.1"
description = "A differentially private data synthesizer and fairness intervention benchmark framework"
authors = [
  { name="Vinicius Gabriel Angelozzi Verona de Resende", email="verona.projects@tutanota.com" },
  { name="Héber Hwang Arcolezi", email="heber.hwang-arcolezi@etsmtl.ca" }
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "aif360>=0.6.1",
  "aif360[inFairness]>=0.6.1",
  "fairlearn>=0.12.0",
  "inFairness>=0.2.3",
  "matplotlib>=3.9.4",
  "matplotlib-inline>=0.1.7",
  "numpy>=1.26.4",
  "pandas>=2.2.3",
  "scikit-learn>=1.6.1",
  "scipy>=1.13.1",
  "smartnoise-sql>=1.0.6",
  "smartnoise-synth>=1.0.5",
  "tabulate>=0.9.0",
  "ucimlrepo>=0.0.7",
  "xgboost>=2.1.1",
  "tensorflow>=2.19.0",
  "tensorflow-io-gcs-filesystem>=0.37.1",
  "cvxpy>=1.6.5",
  "jax>=0.4.30,<0.5",
  "jaxlib>=0.4.30,<0.5",
  "chex>=0.1.87"

]
license = { file = "LICENSE" }

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://github.com/vinicius-verona/dp-fair-intervention-benchmark"
Issues = "https://github.com/vinicius-verona/dp-fair-intervention-benchmark/issues"